name: Auto Sync Upstream

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch:     # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/xyq254245/xyqonlinerule.git
          git fetch upstream

      - name: Check if upstream is ahead
        id: check
        run: |
          git checkout main
          UPSTREAM_HASH=$(git rev-parse upstream/main)
          LOCAL_HASH=$(git rev-parse HEAD)
          echo "Upstream: $UPSTREAM_HASH"
          echo "Local:    $LOCAL_HASH"

          if [ "$UPSTREAM_HASH" != "$LOCAL_HASH" ]; then
            echo "Upstream has new commits."
            echo "needs_update=true" >> $GITHUB_OUTPUT
          else
            echo "No updates found."
            echo "needs_update=false" >> $GITHUB_OUTPUT
          fi

      - name: Merge and Push
        if: steps.check.outputs.needs_update == 'true'
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git merge upstream/main --allow-unrelated-histories -m "Sync from upstream $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main

  cleanup_runs:
    runs-on: ubuntu-latest
    needs: sync
    steps:
      - name: Delete old workflow runs (keep last 10)
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 0
          keep_minimum_runs: 10
